from __future__ import annotations

MODE_B_CONTROLLED_STOP_EXIT_ACK_ENV = "MODE_B_CONTROLLED_STOP_EXIT_ACK"
MODE_B_CONTROLLED_STOP_EXIT_ACK_VALUE = "I_APPROVE_MODE_B_CONTROLLED_STOP_EXIT_APPLY"
C43_AUTONOMOUS_ENTRY_SUBMIT_ACK_ENV = "PHASE_C43_RUNTIME_SUBMIT_ACK"
C43_AUTONOMOUS_ENTRY_SUBMIT_ACK_VALUE = "I_UNDERSTAND_AND_APPROVE_C43_RESTING_LIMIT_BUY_SUBMIT"
D3_CONTROLLED_LIVE_EXIT_ACK_ENV = "PHASE_D3_RUNTIME_SUBMIT_ACK"
D3_CONTROLLED_LIVE_EXIT_ACK_VALUE = "I_UNDERSTAND_AND_APPROVE_D3_CONTROLLED_REDUCE_ONLY_LIVE_EXITS"
MODE_C_MARKET_ORDER_ACK_ENV = "MODE_C_MARKET_ORDER_ACK"
MODE_C_MARKET_ORDER_ACK_VALUE = "I_APPROVE_MARKET_ORDERS_FOR_POC_20_100_NO_REPLICATION"


__all__ = [
    "MODE_B_CONTROLLED_STOP_EXIT_ACK_ENV",
    "MODE_B_CONTROLLED_STOP_EXIT_ACK_VALUE",
    "C43_AUTONOMOUS_ENTRY_SUBMIT_ACK_ENV",
    "C43_AUTONOMOUS_ENTRY_SUBMIT_ACK_VALUE",
    "D3_CONTROLLED_LIVE_EXIT_ACK_ENV",
    "D3_CONTROLLED_LIVE_EXIT_ACK_VALUE",
    "MODE_C_MARKET_ORDER_ACK_ENV",
    "MODE_C_MARKET_ORDER_ACK_VALUE",
]
