#!/usr/bin/env python3
"""Build a deterministic, read-only summary of the bot's most recent cycle.

This tool makes NO LLM calls, NO Coinbase calls, and writes nothing. It only
reads existing local state/log data and reuses two already-vetted read-only
tools (show_autonomous_live_run_status, show_full_pipeline_health) to explain,
in plain text lines, what the bot did and decided in its latest cycle.

This is an evidence summary of logs and recorded decisions -- not a model's
chain of thought. Nothing here is generated by an LLM.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tools.show_autonomous_live_run_status import build_autonomous_live_run_status
from tools.show_full_pipeline_health import build_full_pipeline_health_report

PHASE = "latest_run_summary_v1"
STATE_DECISION_OUTCOMES = Path("state/decision_outcomes.json")
CYCLE_LOOKBACK_MINUTES = 90
CYCLE_FORWARD_BUFFER_MINUTES = 5
MAX_SUMMARY_LINES = 50


def _now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _parse_ts(value: Any) -> Optional[datetime]:
    if not value:
        return None
    text = str(value).strip()
    if not text:
        return None
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    try:
        dt = datetime.fromisoformat(text)
    except ValueError:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc)


def _load_decision_records(root: Path) -> List[Dict[str, Any]]:
    path = root / STATE_DECISION_OUTCOMES
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return []
    records = data.get("records") if isinstance(data, dict) else None
    return records if isinstance(records, list) else []


def _determine_cycle_anchor(live: Dict[str, Any]) -> tuple[str, Optional[datetime]]:
    """Pick whichever of last_full_cycle_time / last_heartbeat_time is most
    recent as the anchor for "this run", and label the cycle type accordingly."""
    full_ts = _parse_ts(live.get("last_full_cycle_time"))
    heartbeat_ts = _parse_ts(live.get("last_heartbeat_time"))
    if full_ts and heartbeat_ts:
        if heartbeat_ts > full_ts:
            return "heartbeat", heartbeat_ts
        return "full", full_ts
    if full_ts:
        return "full", full_ts
    if heartbeat_ts:
        return "heartbeat", heartbeat_ts
    return "unknown", None


def _latest_decisions_for_cycle(records: List[Dict[str, Any]], anchor: Optional[datetime]) -> List[Dict[str, Any]]:
    """Latest record per ticker, restricted to the window around `anchor` so
    a ticker untouched this cycle doesn't drag in a much older decision."""
    if anchor is None:
        window_start = None
        window_end = None
    else:
        window_start = anchor - timedelta(minutes=CYCLE_LOOKBACK_MINUTES)
        window_end = anchor + timedelta(minutes=CYCLE_FORWARD_BUFFER_MINUTES)

    latest_by_ticker: Dict[str, Dict[str, Any]] = {}
    for record in records:
        ticker = record.get("ticker")
        if not ticker:
            continue
        ts = _parse_ts(record.get("created_at"))
        if window_start is not None and ts is not None and not (window_start <= ts <= window_end):
            continue
        existing = latest_by_ticker.get(ticker)
        if existing is None or (record.get("created_at") or "") >= (existing.get("created_at") or ""):
            latest_by_ticker[ticker] = record
    return sorted(latest_by_ticker.values(), key=lambda r: r.get("ticker") or "")


def _ticker_reason(record: Dict[str, Any]) -> str:
    trade_plan = record.get("trade_plan") or {}
    entry_gate = record.get("entry_gate") or {}
    judge = record.get("judge") or {}
    if trade_plan.get("trigger"):
        return str(trade_plan["trigger"])[:160]
    if judge.get("decision") and judge.get("decision") != record.get("decision"):
        return f"judge={judge.get('decision')} confidence={judge.get('confidence')}"
    if entry_gate.get("setup_type"):
        return f"gate={entry_gate.get('decision')} setup={entry_gate.get('setup_type')}"
    return str(record.get("decision_category") or "no specific reason recorded")


def _dominant_setup_type(decisions: List[Dict[str, Any]]) -> str:
    counts: Dict[str, int] = {}
    for record in decisions:
        setup = (record.get("entry_gate") or {}).get("setup_type") or (record.get("trade_plan") or {}).get(
            "setup_type"
        )
        if setup:
            counts[setup] = counts.get(setup, 0) + 1
    if not counts:
        return "unknown"
    return max(counts.items(), key=lambda kv: kv[1])[0]


def _overall_decision(cycle_summary: Dict[str, Any]) -> str:
    if int(cycle_summary.get("approve_trade") or 0) > 0:
        return "approve_trade"
    if int(cycle_summary.get("close_position") or 0) > 0:
        return "close_position"
    if int(cycle_summary.get("reduce_size") or 0) > 0:
        return "reduce_size"
    reject = int(cycle_summary.get("reject") or 0)
    wait = int(cycle_summary.get("wait") or 0)
    if reject > 0 and reject >= wait:
        return "reject"
    if wait > 0:
        return "wait"
    return "no_decisions_recorded"


def _notable_guards(live: Dict[str, Any], pipeline: Dict[str, Any]) -> List[str]:
    guards: List[str] = []
    market_flags = pipeline.get("market_order_flags_enabled") or []
    guards.append("market_orders_disabled" if not market_flags else "market_orders_enabled")
    guards.append(f"open_positions={pipeline.get('open_positions', 0)}")
    guards.append(f"open_orders={pipeline.get('open_orders', 0)}")
    approved = live.get("approved_profile_status") or {}
    if approved.get("hash_valid") and approved.get("loaded"):
        guards.append("approved_profile_valid")
    else:
        guards.append("approved_profile_not_confirmed")
    replication = live.get("replication_status") or {}
    guards.append(
        "replication_disabled" if not replication.get("replication_enabled") else "replication_enabled"
    )
    if live.get("stale_lock_detected"):
        guards.append("stale_process_lock_detected")
    return guards


def _operator_takeaway(overall_decision: str, pipeline: Dict[str, Any]) -> str:
    open_positions = int(pipeline.get("open_positions") or 0)
    open_orders = int(pipeline.get("open_orders") or 0)
    if overall_decision == "approve_trade":
        return "Bot approved at least one new trade this cycle -- review Positions & Orders."
    if overall_decision == "close_position":
        return "Bot closed at least one position this cycle -- review Positions & Orders."
    if overall_decision == "reduce_size":
        return "Bot reduced an existing position's size this cycle -- review Positions & Orders."
    if overall_decision == "reject":
        return "Bot actively rejected candidate setups this cycle -- no new exposure taken."
    if overall_decision == "no_decisions_recorded":
        return "No per-ticker decisions were recorded for this cycle window."
    if open_positions == 0 and open_orders == 0:
        return "Bot is running normally; no open exposure and no strong setup found this cycle."
    return f"Bot waited this cycle while holding {open_positions} position(s) and {open_orders} order(s)."


def build_latest_run_summary(*, root: str | Path = ".") -> Dict[str, Any]:
    root_path = Path(root)
    live = build_autonomous_live_run_status(root=root_path)
    pipeline = build_full_pipeline_health_report(root=root_path)

    cycle_type, anchor = _determine_cycle_anchor(live)
    records = _load_decision_records(root_path)
    decisions = _latest_decisions_for_cycle(records, anchor)

    cycle_summary = live.get("last_cycle_summary") or {}
    gate_summary = live.get("last_gate_summary") or {}
    overall_decision = _overall_decision(cycle_summary)
    market_regime = _dominant_setup_type(decisions)
    guards = _notable_guards(live, pipeline)

    ticker_highlights = [
        {
            "ticker": record.get("ticker"),
            "decision": record.get("decision"),
            "reason": _ticker_reason(record),
        }
        for record in decisions
    ]

    lines: List[str] = []
    lines.append(f"1. Cycle type: {cycle_type} (anchor: {anchor.isoformat() if anchor else 'unknown'}).")
    lines.append(f"2. Bot evaluated {len(decisions)} ticker(s) in this window.")
    if cycle_summary:
        lines.append(
            "3. Decision breakdown: "
            f"approve_trade={cycle_summary.get('approve_trade', 0)}, "
            f"wait={cycle_summary.get('wait', 0)}, "
            f"reject={cycle_summary.get('reject', 0)}, "
            f"reduce_size={cycle_summary.get('reduce_size', 0)}, "
            f"close_position={cycle_summary.get('close_position', 0)}, "
            f"executed={cycle_summary.get('executed', 0)}, "
            f"errors={cycle_summary.get('errors', 0)}."
        )
    else:
        lines.append("3. No cycle decision-breakdown counters were available.")
    if gate_summary:
        lines.append(
            "4. Hard-gate breakdown: "
            f"priority_analyze={gate_summary.get('priority_analyze', 0)}, "
            f"analyze={gate_summary.get('analyze', 0)}, "
            f"watch={gate_summary.get('watch', 0)}, "
            f"skip={gate_summary.get('skip', 0)}."
        )
    lines.append(f"5. Open exposure right now: {pipeline.get('open_positions', 0)} position(s), "
                 f"{pipeline.get('open_orders', 0)} order(s).")
    lines.append(f"6. Dominant setup/regime observed across tickers this cycle: {market_regime}.")
    for guard in guards:
        lines.append(f"{len(lines) + 1}. Guard: {guard}.")
    if not decisions:
        lines.append(f"{len(lines) + 1}. No per-ticker decision records fell inside the cycle window.")
    for record in decisions:
        if len(lines) >= MAX_SUMMARY_LINES - 1:
            lines.append(f"{len(lines) + 1}. ... additional ticker lines truncated at {MAX_SUMMARY_LINES} lines.")
            break
        lines.append(
            f"{len(lines) + 1}. {record.get('ticker')}: {record.get('decision')} -- {_ticker_reason(record)}"
        )
    operator_takeaway = _operator_takeaway(overall_decision, pipeline)
    lines.append(f"{len(lines) + 1}. Conclusion: {operator_takeaway}")

    return {
        "phase": PHASE,
        "generated_at": _now_iso(),
        "read_only": True,
        "llm_call_made": False,
        "coinbase_call_attempted": False,
        "state_write_performed": False,
        "cycle_id": anchor.isoformat() if anchor else None,
        "cycle_type": cycle_type,
        "overall_decision": overall_decision,
        "market_regime": market_regime,
        "summary_lines": lines[:MAX_SUMMARY_LINES],
        "ticker_highlights": ticker_highlights,
        "notable_guards": guards,
        "operator_takeaway": operator_takeaway,
        "source_tools": [
            "tools/show_autonomous_live_run_status.py",
            "tools/show_full_pipeline_health.py",
            "state/decision_outcomes.json",
        ],
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help=argparse.SUPPRESS)
    parser.add_argument("--json", action="store_true", help="print JSON to stdout")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    report = build_latest_run_summary(root=args.root)
    if args.json:
        print(json.dumps(report, indent=2, default=str))
    else:
        for line in report["summary_lines"]:
            print(line)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
