#!/usr/bin/env python3
"""Build the latest Learning Evidence Summary.

A short, plain-language, deterministic note set answering: what did the
bot's learning layer observe this run, which parameter pressure increased
or decreased since the last check, and which setups were missed or
correctly avoided. This is an evidence summary of logs and recorded
decisions -- explicitly NOT a model's chain of thought, and nothing here is
generated by an LLM.

Read-only, no LLM calls, no Coinbase calls, no trading-state mutation. It
does persist one small snapshot file under reports/learning/ purely so it
can report deltas ("which signals got stronger") between runs -- that
snapshot is a report artifact, not bot/trading state.

Writes:
  reports/learning/learning-evidence-summary-latest.json
  reports/learning/learning-evidence-summary-latest.md
  reports/learning/.learning-evidence-snapshot.json  (internal delta state)
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from bot.adaptive_learning_intelligence import build_adaptive_learning_intelligence
from bot.atomic_io import atomic_write_json, atomic_write_text
from bot.regime_parameter_profiles import build_regime_parameter_profiles

REPORT_JSON_PATH = Path("reports/learning/learning-evidence-summary-latest.json")
REPORT_MD_PATH = Path("reports/learning/learning-evidence-summary-latest.md")
SNAPSHOT_PATH = Path("reports/learning/.learning-evidence-snapshot.json")

CONFIDENCE_DELTA_NOTABLE = 0.05


def _now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _read_snapshot(root: Path) -> Dict[str, Any]:
    path = root / SNAPSHOT_PATH
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    return data if isinstance(data, dict) else {}


def _build_snapshot(intelligence: Dict[str, Any]) -> Dict[str, Any]:
    depth = intelligence.get("learning_depth", {})
    parameters = {
        item["parameter"]: {
            "direction": item["direction"],
            "confidence": item["confidence"],
            "evidence_count": item["evidence_count"],
            "tier": item["tier"],
        }
        for item in intelligence.get("parameter_evidence", [])
    }
    return {
        "generated_at": intelligence.get("generated_at"),
        "decision_outcomes_resolved": depth.get("decision_outcomes_resolved", 0),
        "execution_outcomes_count": depth.get("execution_outcomes_count", 0),
        "parameters": parameters,
    }


def _parameter_pressure_deltas(previous: Dict[str, Any], current: Dict[str, Any]) -> List[Dict[str, Any]]:
    prev_params = previous.get("parameters", {}) if previous else {}
    deltas: List[Dict[str, Any]] = []
    for name, now in current.get("parameters", {}).items():
        before = prev_params.get(name)
        if before is None:
            if now["direction"] in ("loosen", "tighten"):
                deltas.append(
                    {
                        "parameter": name,
                        "change": "new_directional_signal",
                        "direction": now["direction"],
                        "confidence": now["confidence"],
                    }
                )
            continue
        confidence_delta = round(now["confidence"] - before.get("confidence", 0.0), 4)
        evidence_delta = now["evidence_count"] - before.get("evidence_count", 0)
        direction_changed = now["direction"] != before.get("direction")
        if direction_changed or abs(confidence_delta) >= CONFIDENCE_DELTA_NOTABLE or evidence_delta:
            deltas.append(
                {
                    "parameter": name,
                    "change": "direction_changed" if direction_changed else "confidence_or_evidence_shift",
                    "direction": now["direction"],
                    "previous_direction": before.get("direction"),
                    "confidence_delta": confidence_delta,
                    "evidence_count_delta": evidence_delta,
                }
            )
    return deltas


def build_latest_learning_evidence_summary(*, root: str | Path = ".") -> Dict[str, Any]:
    root_path = Path(root)
    intelligence = build_adaptive_learning_intelligence(root=root_path)
    regime_profiles = build_regime_parameter_profiles(root=root_path)

    previous_snapshot = _read_snapshot(root_path)
    current_snapshot = _build_snapshot(intelligence)
    deltas = _parameter_pressure_deltas(previous_snapshot, current_snapshot)

    depth = intelligence.get("learning_depth", {})
    wait_quality = intelligence.get("wait_decision_quality", {})
    missed = intelligence.get("missed_opportunity_learning", {})

    new_decision_evidence = depth.get("decision_outcomes_resolved", 0) - previous_snapshot.get(
        "decision_outcomes_resolved", depth.get("decision_outcomes_resolved", 0)
    )
    new_execution_evidence = depth.get("execution_outcomes_count", 0) - previous_snapshot.get(
        "execution_outcomes_count", depth.get("execution_outcomes_count", 0)
    )

    decision_evidence_summary = [
        f"{depth.get('decision_outcomes_resolved', 0)} resolved decision outcome(s), "
        f"{depth.get('decision_outcomes_pending', 0)} still pending resolution.",
        (
            f"Wait decision quality: {wait_quality.get('wait_decision_quality_pct')} correct "
            f"({wait_quality.get('correct_count')}/{wait_quality.get('correct_count', 0) + wait_quality.get('missed_opportunity_count', 0)})."
            if wait_quality.get("wait_decision_quality_pct") is not None
            else "Not enough resolved wait-like decisions yet to score wait quality."
        ),
        f"Missed opportunities recorded: {missed.get('missed_opportunity_count', 0)}.",
    ]

    run_evidence_summary = [
        f"New resolved decision evidence since last check: {new_decision_evidence}.",
        f"New execution evidence since last check: {new_execution_evidence}.",
        f"Regime coverage across current evidence: {depth.get('regime_coverage', {}).get('coverage_pct', 0.0)}.",
    ]

    learning_evidence_summary: List[str] = []
    learning_evidence_summary.extend(decision_evidence_summary)
    if deltas:
        strengthened = [d for d in deltas if d.get("change") == "new_directional_signal" or d.get("confidence_delta", 0) > 0]
        weakened = [d for d in deltas if d.get("confidence_delta", 0) is not None and d.get("confidence_delta", 0) < 0]
        if strengthened:
            learning_evidence_summary.append(
                f"Parameter pressure increased for: {', '.join(d['parameter'] for d in strengthened)}."
            )
        if weakened:
            learning_evidence_summary.append(
                f"Parameter pressure weakened for: {', '.join(d['parameter'] for d in weakened)}."
            )
    else:
        learning_evidence_summary.append("No parameter pressure changes detected since the last check.")

    if regime_profiles.get("narrative_lines"):
        learning_evidence_summary.extend(regime_profiles["narrative_lines"][:5])
    else:
        learning_evidence_summary.append(
            "No regime-segmented learning notes yet -- regime tagging coverage on current evidence is too sparse."
        )

    if missed.get("by_ticker"):
        top_ticker = next(iter(missed["by_ticker"]))
        learning_evidence_summary.append(
            f"Setup most often missed this evidence window: {top_ticker} "
            f"({missed['by_ticker'][top_ticker]} missed_opportunity record(s))."
        )

    report = {
        "schema_version": "learning_evidence_summary_v1",
        "generated_at": _now_iso(),
        "read_only": True,
        "llm_call_made": False,
        "coinbase_call_attempted": False,
        "state_write_performed": False,
        "decision_evidence_summary": decision_evidence_summary,
        "run_evidence_summary": run_evidence_summary,
        "learning_evidence_summary": learning_evidence_summary,
        "parameter_pressure_deltas": deltas,
    }
    return report, current_snapshot


def render_markdown(report: Dict[str, Any]) -> str:
    lines = ["# Learning Evidence Summary", ""]
    lines.append(f"Generated: `{report.get('generated_at')}`")
    lines.append("")
    lines.append(
        "Deterministic evidence summary -- not a model's chain of thought. No LLM calls, no "
        "Coinbase calls, no trading-state mutation."
    )
    lines.append("")
    lines.append("## Learning evidence summary")
    for line in report.get("learning_evidence_summary", []):
        lines.append(f"- {line}")
    lines.append("")
    lines.append("## Decision evidence summary")
    for line in report.get("decision_evidence_summary", []):
        lines.append(f"- {line}")
    lines.append("")
    lines.append("## Run evidence summary")
    for line in report.get("run_evidence_summary", []):
        lines.append(f"- {line}")
    lines.append("")
    if report.get("parameter_pressure_deltas"):
        lines.append("## Parameter pressure deltas")
        for delta in report["parameter_pressure_deltas"]:
            lines.append(f"- `{delta['parameter']}`: {delta}")
        lines.append("")
    return "\n".join(lines) + "\n"


def write_reports(report: Dict[str, Any], snapshot: Dict[str, Any], *, root: Path) -> None:
    atomic_write_json(root / REPORT_JSON_PATH, report)
    atomic_write_text(root / REPORT_MD_PATH, render_markdown(report))
    atomic_write_json(root / SNAPSHOT_PATH, snapshot)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help=argparse.SUPPRESS)
    parser.add_argument("--json", action="store_true", help="print JSON to stdout")
    parser.add_argument("--no-write", action="store_true", help="skip writing report files (used in tests)")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root_path = Path(args.root)
    report, snapshot = build_latest_learning_evidence_summary(root=root_path)
    if not args.no_write:
        write_reports(report, snapshot, root=root_path)
    if args.json:
        print(json.dumps(report, indent=2, default=str))
    else:
        for line in report["learning_evidence_summary"]:
            print(line)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
